swagger: "2.0"
info:
  version: 1.0.0
  title: Rowcord API
  description: Rowcord API
host: localhost
schemes:
  - http
consumes:
  - application/json
basePath: /v1
produces:
  - application/json
paths:
  /test/register:
    post:
      summary: Create a test account
      parameters:
        - name: body
          in: body
          schema:
            properties:
              email:
                type: string
                minLength: 1
                maxLength: 254
              password:
                type: string
                minLength: 1
                maxLength: 255
      x-examples:
        application/json: |-
          {
            "email": "email@provider.com",
            "password": "mypassword"
          }
      responses:
        201:
          description: Account created
        default:
          description: Account creation failed
  /test/login:
    post:
      summary: Logs into account
      parameters:
        - name: body
          in: body
          schema:
            properties:
              email:
                type: string
              password:
                type: string
      x-examples:
         application/json: |-
          {
            "email": "email@provider.com",
            "password": "mypassword"
          }
      responses:
        201:
          description: Logged in
        default:
          description: Account login failed
  /groups:
    post:
      summary: Creates a group
      parameters:
        - name: body
          in: body
          schema:
            properties:
              name:
                type: string
              description:
                type: string
              groupType:
                type: string
                enum: [ "open", "closed", "secret" ]
      responses:
        201:
          description: Group created
        default:
          description: Group creation failed
  /group/{groupId}:
    put:
      summary: Update a group
      parameters:
        - name: groupId
          in: path
          required: true
          type: number
        - name: body
          in: body
          schema:
            properties:
              name:
                type: string
              description:
                type: string
              groupType:
                type: string
                enum: [ "open", "closed", "secret" ]
      responses:
        201:
          description: Group updated
        default:
          description: Group update failed
  /group/invite:
    post:
      summary: Invite users to group
      parameters:
        - name: body
          in: body
          schema:
            properties:
              groupId:
                type: number
              userIds:
                type: number # a list of numbers
      responses:
        201:
          description: Successfully invited
        default:
          description: Failed to invite
  /group/join:
    post:
      summary: Join a group
      parameters:
        - name: body
          in: body
          schema:
            properties:
              groupId:
                type: number
      responses:
        201:
          description: Successfully joined group
        default:
          description: Failed to join groupo
  /group/approve:
    post:
      summary: Approve a request to join a group
      parameters:
        - name: body
          in: body
          schema:
            properties:
              groupId:
                type: number
              userId:
                type: number
      responses:
        201:
          description: Successfully approved request to join
        default:
          description: Failed to approve request to join
  /group/remove:
    post:
      summary: Remove a member from a group
      parameters:
        - name: body
          in: body
          schema:
            properties:
              groupId:
                type: number
              userId:
                type: number
      responses:
        201:
          description: Successfully removed member from group
        default:
          description: Failed to remove member from group
  /subgroup:
    post:
      summary: Create a subgroup within the group
      parameters:
        - name: body
          in: body
          schema:
            properties:
              groupId:
                type: number
              subgroupName:
                type: string
              subgroupDescription:
                type: string
      responses:
        201:
          description: Successfully created subgroup
        default:
          description: Failed to create subgroup
  /subgroup/members:
    post:
      summary: Add members to a subgroup
      parameters:
        - name: body
          in: body
          schema:
            properties:
              groupId:
                type: number
              userIds:
                type: number # a list of numbers
      responses:
        201:
          description: Successfully added members to subgroup
        default:
          description: Failed to add members to subgroup
    delete:
      summary: Removes members from a subgroup
      parameters:
        - name: body
          in: body
          schema:
            properties:
              groupId:
                type: number
              userIds:
                type: number # a list of numbers
      responses:
        201:
          description: Successfully removed members from subgroup
        default:
          description: Failed to remove members from subgroup
  /users/permissions:
    put:
      summary: Sets permissions for user
      parameters:
        - name: body
          in: body
          schema:
            properties:
              userId:
                type: number
              groupId:
                type: number
              permissions:
                type: string # a map from permissionName to boolean
      responses:
        201:
          description: Successfully set permissions for user
        default:
          description: Failed to set permissions for user
  /subgroup/permissions:
    put:
      summary: Sets permissions for subgroup
      parameters:
        - name: body
          in: body
          schema:
            properties:
              subgroupId:
                type: number
              groupId:
                type: number
              permissions:
                type: string # a map from permissionName to boolean
      responses:
        201:
          description: Successfully set permissions for subgroup
        default:
          description: Failed to set permissions for subgroup